#!/bin/bash
# Deploy Eclipse Che with IPv6 support on OpenShift using chectl
#
# This script deploys Eclipse Che on OpenShift clusters with IPv6 support
# using the PR-1442 dashboard image that includes IPv6 URL validation.
#
# Prerequisites:
# - oc CLI configured and connected to an OpenShift cluster
# - chectl installed (https://github.com/che-incubator/chectl)
# - OpenShift cluster with IPv6 networking support
#   (launched via cluster bot: "launch 4.20.2 metal,ipv6")
#
# Usage:
#   ./deploy-che-ipv6-chectl.sh [options]
#
# Options:
#   --namespace <namespace>      Che namespace (default: eclipse-che)
#   --dashboard-image <image>    Dashboard image (default: quay.io/eclipse/che-dashboard:pr-1442)
#   --che-operator-image <image> Che operator image (default: quay.io/eclipse/che-operator:next)
#   --skip-ipv6-check           Skip IPv6 cluster verification
#   --skip-mirror               Skip image mirroring (use if images already mirrored)
#   --local-registry <registry>  Local registry for image mirroring (auto-detected if not specified)
#   --help                       Show this help message
#
# Generated by Claude Sonnet 4.5

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
NAMESPACE="${CHE_NAMESPACE:-eclipse-che}"
DASHBOARD_IMAGE="${DASHBOARD_IMAGE:-quay.io/eclipse/che-dashboard:pr-1442}"
CHE_OPERATOR_IMAGE="${CHE_OPERATOR_IMAGE:-quay.io/eclipse/che-operator:next}"
SKIP_IPV6_CHECK=false
SKIP_MIRROR=false
LOCAL_REGISTRY=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --dashboard-image)
            DASHBOARD_IMAGE="$2"
            shift 2
            ;;
        --che-operator-image)
            CHE_OPERATOR_IMAGE="$2"
            shift 2
            ;;
        --skip-ipv6-check)
            SKIP_IPV6_CHECK=true
            shift
            ;;
        --skip-mirror)
            SKIP_MIRROR=true
            shift
            ;;
        --local-registry)
            LOCAL_REGISTRY="$2"
            shift 2
            ;;
        --help)
            grep '^#' "$0" | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Deploy Eclipse Che with IPv6 Support on OpenShift        ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo "  Platform:         OpenShift"
echo "  Namespace:        ${NAMESPACE}"
echo "  Dashboard image:  ${DASHBOARD_IMAGE}"
echo "  Operator image:   ${CHE_OPERATOR_IMAGE}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Step 1: Checking prerequisites${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# Check oc CLI
if ! command -v oc &> /dev/null; then
    echo -e "${RED}Error: oc command not found${NC}"
    echo "Please install oc CLI: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/"
    exit 1
fi
echo -e "${GREEN}✓ oc CLI found: $(oc version --client | head -1)${NC}"

# Check chectl
if ! command -v chectl &> /dev/null; then
    echo -e "${RED}Error: chectl not found${NC}"
    echo ""
    echo "Install chectl:"
    echo "  # Using installer script"
    echo "  bash <(curl -sL https://che-incubator.github.io/chectl/install.sh)"
    echo ""
    echo "  # Or using npm"
    echo "  npm install -g chectl"
    exit 1
fi
echo -e "${GREEN}✓ chectl found: $(chectl version)${NC}"

# Check cluster connectivity
if ! oc whoami &> /dev/null; then
    echo -e "${RED}Error: Not logged into OpenShift cluster${NC}"
    echo ""
    echo "Please login to your cluster:"
    echo "  # If using cluster bot, set kubeconfig:"
    echo "  export KUBECONFIG=/path/to/cluster-bot-kubeconfig"
    echo ""
    echo "  # Verify connection:"
    echo "  oc whoami"
    echo "  oc get nodes"
    exit 1
fi
echo -e "${GREEN}✓ Logged into OpenShift as $(oc whoami)${NC}"

CLUSTER_VERSION=$(oc version | grep "Server Version" | awk '{print $3}' || echo "Unknown")
echo "  Cluster version: ${CLUSTER_VERSION}"
echo ""

# Step 2: Check IPv6 support
echo -e "${YELLOW}Step 2: Checking cluster IPv6 support${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# Check for IPv6 service network
IPV6_SERVICE_NET=$(oc get network.config.openshift.io cluster -o jsonpath='{.status.serviceNetwork}' 2>/dev/null | grep -o 'fd[0-9a-f:]*' || echo "")

if [ -n "$IPV6_SERVICE_NET" ]; then
    echo -e "${GREEN}✓ Cluster has IPv6 service network: $IPV6_SERVICE_NET${NC}"
    IPV6_ENABLED=true
else
    echo -e "${YELLOW}⚠ No IPv6 service network detected (IPv4-only cluster)${NC}"
    IPV6_ENABLED=false

    if [ "$SKIP_IPV6_CHECK" == "false" ]; then
        echo ""
        echo -e "${YELLOW}This cluster appears to be IPv4-only.${NC}"
        echo "  ✅ IPv6 URL validation will still work"
        echo "  ✅ Backend will bind to :: (dual-stack ready)"
        echo "  ❌ Cannot test actual IPv6 connectivity"
        echo ""
        echo "For dual-stack IPv6 testing, launch cluster with cluster bot:"
        echo "  launch 4.20.2 metal,ipv6"
        echo ""
        read -p "Continue deployment anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "${YELLOW}Deployment cancelled${NC}"
            exit 0
        fi
    fi
fi

# Check pod network
IPV6_POD_NET=$(oc get network.config.openshift.io cluster -o jsonpath='{.status.clusterNetwork[*].cidr}' 2>/dev/null | grep -o 'fd[0-9a-f:]*' || echo "")
if [ -n "$IPV6_POD_NET" ]; then
    echo -e "${GREEN}✓ Cluster has IPv6 pod network: $IPV6_POD_NET${NC}"
fi

# Check IP family policy
DUAL_STACK=$(oc get svc -A -o jsonpath='{.items[*].spec.ipFamilyPolicy}' 2>/dev/null | grep -i dual || echo "")
if [ -n "$DUAL_STACK" ]; then
    echo -e "${GREEN}✓ Cluster supports dual-stack services${NC}"
fi

echo ""

# Step 3: Check if image mirroring is needed
echo -e "${YELLOW}Step 3: Checking image mirroring requirements${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

if [ "$SKIP_MIRROR" == "true" ]; then
    echo -e "${YELLOW}⚠ Image mirroring skipped (--skip-mirror flag)${NC}"
    echo ""
else
    # Check if local registry exists
    if [ -z "$LOCAL_REGISTRY" ]; then
        echo -e "${YELLOW}Auto-detecting local registry...${NC}"
        LOCAL_REGISTRY=$(oc get imagecontentsourcepolicy -o jsonpath='{.items[0].spec.repositoryDigestMirrors[0].mirrors[0]}' 2>/dev/null | sed 's|/.*||' || echo "")
    fi

    if [ -n "$LOCAL_REGISTRY" ]; then
        echo -e "${GREEN}✓ Local registry detected: ${LOCAL_REGISTRY}${NC}"

        # Check if this is an IPv6-only cluster
        IPV4_SERVICE=$(oc get network.config.openshift.io cluster -o jsonpath='{.status.serviceNetwork}' 2>/dev/null | grep -v 'fd[0-9a-f:]*' | grep -E '([0-9]{1,3}\.){3}[0-9]{1,3}' || echo "")

        if [ -z "$IPV4_SERVICE" ]; then
            echo -e "${YELLOW}⚠ IPv6-only cluster detected - image mirroring required${NC}"
            echo "  Public container registries don't support IPv6"
            echo "  Will mirror images to local registry: ${LOCAL_REGISTRY}"
            echo ""

            # Check if mirror script exists
            SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
            MIRROR_SCRIPT="${SCRIPT_DIR}/mirror-images-to-registry.sh"

            if [ ! -f "$MIRROR_SCRIPT" ]; then
                echo -e "${RED}Error: Mirror script not found: ${MIRROR_SCRIPT}${NC}"
                echo "Please ensure mirror-images-to-registry.sh is in the same directory"
                exit 1
            fi

            echo -e "${YELLOW}Running image mirroring script...${NC}"
            echo "This will take 15-30 minutes to mirror all images"
            echo ""

            # Run the mirror script
            bash "$MIRROR_SCRIPT" \
                --registry "${LOCAL_REGISTRY}" \
                --namespace "${NAMESPACE}" \
                --dashboard-image "${DASHBOARD_IMAGE}"

            MIRROR_EXIT_CODE=$?

            if [ $MIRROR_EXIT_CODE -ne 0 ]; then
                echo -e "${RED}Error: Image mirroring failed (exit code: ${MIRROR_EXIT_CODE})${NC}"
                echo ""
                echo "Common issues:"
                echo "  - Machine doesn't have IPv4 access to pull from quay.io"
                echo "  - Registry credentials are incorrect"
                echo "  - Network connectivity issues"
                echo ""
                echo "To skip mirroring and continue anyway, use: --skip-mirror"
                exit 1
            fi

            echo ""
            echo -e "${GREEN}✓ Image mirroring completed${NC}"
            echo -e "${YELLOW}⚠ Nodes are rebooting to apply new image policy${NC}"
            echo "  This may take 10-15 minutes"
            echo ""

            # Wait for nodes to be ready after MachineConfigPool update
            echo -e "${YELLOW}Waiting for all nodes to be Ready...${NC}"
            for i in {1..60}; do
                NOT_READY=$(oc get nodes --no-headers 2>/dev/null | grep -v " Ready " | wc -l || echo "1")
                if [ "$NOT_READY" -eq 0 ]; then
                    echo -e "${GREEN}✓ All nodes are Ready${NC}"
                    break
                fi
                echo "  Waiting for nodes to be Ready... ($i/60) - ${NOT_READY} nodes not ready yet"
                sleep 15
            done

            # Verify MachineConfigPools are updated
            echo -e "${YELLOW}Verifying MachineConfigPool status...${NC}"
            oc get mcp 2>/dev/null || true
            echo ""

        else
            echo -e "${GREEN}✓ Cluster has IPv4 connectivity - direct image pull available${NC}"
            echo "  Image mirroring not required"
            echo ""
        fi
    else
        echo -e "${YELLOW}⚠ No local registry detected${NC}"
        echo "  Will attempt direct image pull from quay.io"
        echo "  If deployment fails with ImagePullBackOff, you may need to:"
        echo "    1. Set up a local registry accessible via IPv6"
        echo "    2. Run: ./mirror-images-to-registry.sh --registry <your-registry>"
        echo ""
    fi
fi

# Step 4: Deploy Eclipse Che
echo -e "${YELLOW}Step 4: Deploying Eclipse Che with chectl${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo -e "${YELLOW}Running chectl server:deploy...${NC}"
echo "This may take 5-10 minutes..."
echo ""

# Deploy Che
chectl server:deploy \
    --platform openshift \
    --installer operator \
    --chenamespace ${NAMESPACE} \
    --che-operator-image ${CHE_OPERATOR_IMAGE}

echo ""
echo -e "${GREEN}✓ Che deployment initiated${NC}"
echo ""

# Step 5: Wait for CheCluster to be created
echo -e "${YELLOW}Step 5: Waiting for CheCluster resource${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

for i in {1..60}; do
    if oc get checluster eclipse-che -n ${NAMESPACE} &>/dev/null; then
        echo -e "${GREEN}✓ CheCluster resource created${NC}"
        break
    fi
    echo "  Waiting for CheCluster resource... ($i/60)"
    sleep 2
done

if ! oc get checluster eclipse-che -n ${NAMESPACE} &>/dev/null; then
    echo -e "${RED}Error: CheCluster resource not created${NC}"
    echo "Check operator logs:"
    echo "  oc logs -n ${NAMESPACE} -l app=che-operator --tail=50"
    exit 1
fi

echo ""

# Step 6: Patch dashboard image to PR-1442
echo -e "${YELLOW}Step 6: Updating dashboard image to PR-1442${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo -e "${YELLOW}Patching CheCluster...${NC}"

oc patch checluster eclipse-che -n ${NAMESPACE} --type merge -p "
{
  \"spec\": {
    \"components\": {
      \"dashboard\": {
        \"deployment\": {
          \"containers\": [{
            \"image\": \"${DASHBOARD_IMAGE}\",
            \"imagePullPolicy\": \"Always\",
            \"name\": \"che-dashboard\"
          }]
        }
      }
    }
  }
}"

echo -e "${GREEN}✓ CheCluster patched with PR-1442 dashboard${NC}"
echo ""

# Step 7: Wait for deployment
echo -e "${YELLOW}Step 7: Waiting for pods to be ready${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo -e "${YELLOW}Waiting for dashboard deployment...${NC}"
oc wait --for=condition=Available deployment/che-dashboard -n ${NAMESPACE} --timeout=10m 2>/dev/null || true

echo -e "${YELLOW}Waiting for che server deployment...${NC}"
oc wait --for=condition=Available deployment/che -n ${NAMESPACE} --timeout=10m 2>/dev/null || true

echo -e "${YELLOW}Waiting for gateway deployment...${NC}"
oc wait --for=condition=Available deployment/che-gateway -n ${NAMESPACE} --timeout=10m 2>/dev/null || true

echo ""
echo -e "${GREEN}✓ All deployments ready${NC}"
echo ""

# Step 8: Verify deployment
echo -e "${YELLOW}Step 8: Verifying deployment${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# Get dashboard pod
DASHBOARD_POD=$(oc get pods -n ${NAMESPACE} -l app=che-dashboard -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")

if [ -n "$DASHBOARD_POD" ]; then
    echo -e "${GREEN}✓ Dashboard pod: ${DASHBOARD_POD}${NC}"

    # Check dashboard image
    ACTUAL_IMAGE=$(oc get pod ${DASHBOARD_POD} -n ${NAMESPACE} -o jsonpath='{.spec.containers[0].image}')
    echo "  Image: ${ACTUAL_IMAGE}"

    if [[ "$ACTUAL_IMAGE" == *"pr-1442"* ]]; then
        echo -e "${GREEN}  ✓ Correct dashboard image (pr-1442)${NC}"
    else
        echo -e "${YELLOW}  ⚠ Warning: Expected pr-1442 image, got: ${ACTUAL_IMAGE}${NC}"
    fi

    # Check pod IPs
    POD_IPS=$(oc get pod ${DASHBOARD_POD} -n ${NAMESPACE} -o jsonpath='{.status.podIPs[*].ip}')
    echo "  Pod IPs: ${POD_IPS}"

    if echo "$POD_IPS" | grep -q ":"; then
        echo -e "${GREEN}  ✓ Pod has IPv6 address${NC}"
    else
        echo -e "${YELLOW}  ⚠ Pod has IPv4 address only (IPv4-only cluster)${NC}"
    fi
else
    echo -e "${YELLOW}⚠ Dashboard pod not found yet${NC}"
fi

echo ""

# Display results
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Eclipse Che Deployed Successfully! 🎉             ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Get Che URL
CHE_URL=$(oc get checluster eclipse-che -n ${NAMESPACE} -o jsonpath='{.status.cheURL}' 2>/dev/null || echo "Not available yet")

echo -e "${BLUE}Access Information:${NC}"
echo "  Che URL:       ${CHE_URL}"
echo "  Dashboard:     ${CHE_URL}/dashboard/"
echo "  Namespace:     ${NAMESPACE}"
echo ""

# Get route
ROUTE_HOST=$(oc get route che -n ${NAMESPACE} -o jsonpath='{.spec.host}' 2>/dev/null || echo "N/A")
echo -e "${BLUE}Route:${NC}"
echo "  Host: ${ROUTE_HOST}"
echo ""

echo -e "${BLUE}Dashboard Image:${NC}"
DASHBOARD_IMAGE_ACTUAL=$(oc get deployment che-dashboard -n ${NAMESPACE} -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null || echo "N/A")
echo "  ${DASHBOARD_IMAGE_ACTUAL}"
echo ""

if [[ "$IPV6_ENABLED" == "true" ]]; then
    echo -e "${BLUE}IPv6 Status:${NC}"
    echo -e "${GREEN}  ✓ Cluster supports IPv6${NC}"
    echo "  ✓ Dashboard includes IPv6 URL validation"
    echo "  ✓ Backend supports dual-stack networking"
    echo "  Service network: ${IPV6_SERVICE_NET}"
    echo "  Pod network: ${IPV6_POD_NET}"
else
    echo -e "${BLUE}IPv6 Status:${NC}"
    echo -e "${YELLOW}  ⚠ Cluster is IPv4-only${NC}"
    echo "  ✓ Dashboard includes IPv6 URL validation (frontend)"
    echo "  ✓ Backend binds to :: (dual-stack ready)"
    echo "  ℹ For dual-stack IPv6 testing, use cluster bot:"
    echo "    launch 4.20.2 metal,ipv6"
fi
echo ""

echo -e "${BLUE}Pods in ${NAMESPACE}:${NC}"
oc get pods -n ${NAMESPACE}
echo ""

echo -e "${BLUE}Services:${NC}"
oc get svc -n ${NAMESPACE} -o custom-columns=\
NAME:.metadata.name,\
TYPE:.spec.type,\
IP-POLICY:.spec.ipFamilyPolicy,\
CLUSTER-IPS:.spec.clusterIPs
echo ""

echo -e "${BLUE}Useful Commands:${NC}"
echo "  Check status:       chectl server:status"
echo "  View dashboard logs: oc logs -n ${NAMESPACE} -l app=che-dashboard -f"
echo "  View che logs:      oc logs -n ${NAMESPACE} -l app=che -f"
echo "  Delete Che:         chectl server:delete -n ${NAMESPACE}"
echo "  Cluster info:       oc get checluster eclipse-che -n ${NAMESPACE}"
echo "  Port forward:       oc port-forward -n ${NAMESPACE} svc/che-host 8080:8080"
echo ""

echo -e "${BLUE}Testing:${NC}"
echo "  1. Access dashboard: ${CHE_URL}/dashboard/"
echo "  2. Run IPv6 tests:   ./test-ipv6-validation.sh"
echo "  3. Read testing guide: cat test-ipv6-validation.md"
echo ""

echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Open dashboard and test IPv6 URL validation in browser console"
echo "  2. Test Data Resolver API with IPv6 URLs (see testing-data-resolver-api.md)"
echo "  3. Create workspaces with IPv6 Git repositories"
echo ""

echo -e "${GREEN}✓ Deployment complete!${NC}"
