#!/bin/bash
# IPv6 Validation Testing Script for Eclipse Che Dashboard
#
# This script automates testing of IPv6 support in Eclipse Che Dashboard PR-1442
#
# Prerequisites:
# - Eclipse Che deployed with PR-1442 dashboard image
# - kubectl or oc CLI configured
# - jq installed (for JSON parsing)
#
# Usage:
#   ./test-ipv6-validation.sh [options]
#
# Options:
#   --suite <suite>    Run specific test suite: frontend, backend, api, or all (default: all)
#   --namespace <ns>   Che namespace (default: eclipse-che)
#   --verbose          Show detailed output
#   --help             Show this help message
#
# Generated by Claude Sonnet 4.5

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
TEST_SUITE="all"
NAMESPACE="eclipse-che"
VERBOSE=false
KUBECTL_CMD="kubectl"

# Test counters
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
SKIPPED_TESTS=0

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --suite)
            TEST_SUITE="$2"
            shift 2
            ;;
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help)
            grep '^#' "$0" | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Check if using OpenShift
if command -v oc &> /dev/null && oc whoami &> /dev/null; then
    KUBECTL_CMD="oc"
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       IPv6 Validation Testing for Che Dashboard          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo "  Test Suite:   ${TEST_SUITE}"
echo "  Namespace:    ${NAMESPACE}"
echo "  CLI Tool:     ${KUBECTL_CMD}"
echo ""

# Helper function for test results
record_test() {
    local test_id="$1"
    local description="$2"
    local result="$3"  # PASS, FAIL, SKIP
    local message="$4"

    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    case $result in
        PASS)
            PASSED_TESTS=$((PASSED_TESTS + 1))
            echo -e "${GREEN}✓ $test_id: $description${NC}"
            ;;
        FAIL)
            FAILED_TESTS=$((FAILED_TESTS + 1))
            echo -e "${RED}✗ $test_id: $description${NC}"
            if [ -n "$message" ]; then
                echo -e "${RED}  Error: $message${NC}"
            fi
            ;;
        SKIP)
            SKIPPED_TESTS=$((SKIPPED_TESTS + 1))
            echo -e "${YELLOW}⊝ $test_id: $description (SKIPPED)${NC}"
            if [ -n "$message" ]; then
                echo -e "${YELLOW}  Reason: $message${NC}"
            fi
            ;;
    esac

    if [ "$VERBOSE" == "true" ] && [ -n "$message" ]; then
        echo "  Details: $message"
    fi
}

# Test Suite 1: Frontend URL Validation
test_frontend_validation() {
    echo -e "${YELLOW}Test Suite 1: Frontend URL Validation${NC}"
    echo -e "${YELLOW}════════════════════════════════════════${NC}"
    echo ""

    # Get dashboard pod
    DASHBOARD_POD=$($KUBECTL_CMD get pods -n $NAMESPACE -l app=che-dashboard -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

    if [ -z "$DASHBOARD_POD" ]; then
        record_test "TS1" "Dashboard pod exists" "FAIL" "Dashboard pod not found"
        return
    fi

    record_test "TS1.0" "Dashboard pod exists" "PASS" "$DASHBOARD_POD"

    # Check dashboard image
    DASHBOARD_IMAGE=$($KUBECTL_CMD get pod $DASHBOARD_POD -n $NAMESPACE -o jsonpath='{.spec.containers[0].image}')

    if [[ "$DASHBOARD_IMAGE" == *"pr-1442"* ]]; then
        record_test "TS1.1" "Dashboard image is PR-1442" "PASS" "$DASHBOARD_IMAGE"
    else
        record_test "TS1.1" "Dashboard image is PR-1442" "FAIL" "Found: $DASHBOARD_IMAGE"
    fi

    echo ""
    echo -e "${BLUE}JavaScript Console Tests (manual verification required):${NC}"
    echo "1. Open: https://<che-url>/dashboard/"
    echo "2. Open Browser Console (F12)"
    echo "3. Run the following commands:"
    echo ""
    cat <<'EOF'
const regex = /^(http(s)?:\/\/)((\w[\w.-]*)|(\[[0-9a-fA-F:.]+\]))(:\d+)?([-a-zA-Z0-9@:%._+~#=/[\]?&{}, ]*)$/;
console.log('TC1.1 IPv6 loopback:', regex.test('http://[::1]:8080/repo.git'));  // Expected: true
console.log('TC1.2 IPv6 address:', regex.test('http://[2001:db8::1]/path'));    // Expected: true
console.log('TC1.3 IPv6 with port:', regex.test('https://[fe80::1]:443/'));     // Expected: true
console.log('TC1.4 IPv4-mapped:', regex.test('http://[::ffff:192.168.1.1]:8080/repo.git')); // Expected: true
console.log('TC1.5 Missing brackets:', regex.test('http://::1:8080/repo.git')); // Expected: false
EOF
    echo ""

    record_test "TS1.2" "Browser console tests" "SKIP" "Manual verification required"
    echo ""
}

# Test Suite 2: Backend Dual-Stack Binding
test_backend_binding() {
    echo -e "${YELLOW}Test Suite 2: Backend Dual-Stack Binding${NC}"
    echo -e "${YELLOW}════════════════════════════════════════${NC}"
    echo ""

    # Get dashboard pod
    DASHBOARD_POD=$($KUBECTL_CMD get pods -n $NAMESPACE -l app=che-dashboard -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

    if [ -z "$DASHBOARD_POD" ]; then
        record_test "TS2" "Dashboard pod exists" "FAIL" "Dashboard pod not found"
        return
    fi

    # Test 1: Check if backend is listening on ::
    echo -e "${BLUE}Checking backend socket binding...${NC}"
    SOCKET_INFO=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- sh -c "netstat -tlnp 2>/dev/null || ss -tlnp" 2>/dev/null | grep :8080 || echo "")

    if echo "$SOCKET_INFO" | grep -q ":::8080\|tcp6.*:8080"; then
        record_test "TS2.1" "Backend binds to :: (dual-stack)" "PASS" "Listening on IPv6"
    else
        record_test "TS2.1" "Backend binds to :: (dual-stack)" "FAIL" "Not listening on ::"
    fi

    # Test 2: Check IPv4 access
    IPV4_TEST=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/dashboard/ 2>/dev/null || echo "000")

    if [ "$IPV4_TEST" == "200" ] || [ "$IPV4_TEST" == "302" ]; then
        record_test "TS2.2" "IPv4 access works (localhost)" "PASS" "HTTP $IPV4_TEST"
    else
        record_test "TS2.2" "IPv4 access works (localhost)" "FAIL" "HTTP $IPV4_TEST"
    fi

    # Test 3: Check IPv6 access (may not work on IPv4-only clusters)
    IPV6_TEST=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- curl -s -o /dev/null -w "%{http_code}" "http://[::1]:8080/dashboard/" 2>/dev/null || echo "000")

    if [ "$IPV6_TEST" == "200" ] || [ "$IPV6_TEST" == "302" ]; then
        record_test "TS2.3" "IPv6 access works ([::1])" "PASS" "HTTP $IPV6_TEST"
    elif [ "$IPV6_TEST" == "000" ] || [ "$IPV6_TEST" == "007" ]; then
        record_test "TS2.3" "IPv6 access works ([::1])" "SKIP" "IPv4-only cluster (expected)"
    else
        record_test "TS2.3" "IPv6 access works ([::1])" "FAIL" "HTTP $IPV6_TEST"
    fi

    # Test 4: Check pod IPs
    POD_IPS=$($KUBECTL_CMD get pod $DASHBOARD_POD -n $NAMESPACE -o jsonpath='{.status.podIPs[*].ip}')

    if echo "$POD_IPS" | grep -q ":"; then
        record_test "TS2.4" "Pod has IPv6 address" "PASS" "$POD_IPS"
    else
        record_test "TS2.4" "Pod has IPv6 address" "SKIP" "IPv4-only cluster: $POD_IPS"
    fi

    echo ""
}

# Test Suite 3: Data Resolver API
test_data_resolver_api() {
    echo -e "${YELLOW}Test Suite 3: Data Resolver API${NC}"
    echo -e "${YELLOW}════════════════════════════════════════${NC}"
    echo ""

    # Get dashboard pod
    DASHBOARD_POD=$($KUBECTL_CMD get pods -n $NAMESPACE -l app=che-dashboard -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

    if [ -z "$DASHBOARD_POD" ]; then
        record_test "TS3" "Dashboard pod exists" "FAIL" "Dashboard pod not found"
        return
    fi

    # Test 1: IPv6 URL parsing (expect connection refused - proves parsing works)
    echo -e "${BLUE}Testing IPv6 URL parsing...${NC}"
    API_RESPONSE=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- curl -s -X POST \
        "http://localhost:8080/dashboard/api/data/resolver" \
        -H "Content-Type: application/json" \
        -d '{"url": "http://[::1]:8090/devfile.yaml"}' 2>/dev/null || echo '{"statusCode":0}')

    # Check if response contains ECONNREFUSED (proves IPv6 parsing works)
    if echo "$API_RESPONSE" | grep -q "ECONNREFUSED.*::1:8090"; then
        record_test "TS3.1" "IPv6 URL parsing (ECONNREFUSED)" "PASS" "IPv6 address parsed correctly"
    elif echo "$API_RESPONSE" | grep -q "Invalid URL"; then
        record_test "TS3.1" "IPv6 URL parsing (ECONNREFUSED)" "FAIL" "IPv6 URL rejected (validation error)"
    else
        record_test "TS3.1" "IPv6 URL parsing (ECONNREFUSED)" "SKIP" "Unexpected response: ${API_RESPONSE:0:50}..."
    fi

    # Test 2: IPv4 URL (should work if external connectivity available)
    API_RESPONSE_IPV4=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- curl -s -X POST \
        "http://localhost:8080/dashboard/api/data/resolver" \
        -H "Content-Type: application/json" \
        -d '{"url": "https://raw.githubusercontent.com/devfile/devworkspace-operator/main/devfile.yaml"}' 2>/dev/null || echo '{"statusCode":0}')

    if echo "$API_RESPONSE_IPV4" | grep -q "schemaVersion"; then
        record_test "TS3.2" "IPv4 URL fetching (sanity check)" "PASS" "Successfully fetched devfile"
    else
        record_test "TS3.2" "IPv4 URL fetching (sanity check)" "SKIP" "External connectivity unavailable"
    fi

    # Test 3: Invalid URL (should return 400 or validation error)
    API_RESPONSE_INVALID=$($KUBECTL_CMD exec -n $NAMESPACE $DASHBOARD_POD -- curl -s -X POST \
        "http://localhost:8080/dashboard/api/data/resolver" \
        -H "Content-Type: application/json" \
        -d '{"url": "not-a-valid-url"}' 2>/dev/null || echo '{"statusCode":0}')

    if echo "$API_RESPONSE_INVALID" | grep -qiE "(400|invalid|bad request)"; then
        record_test "TS3.3" "Invalid URL rejection" "PASS" "Invalid URL properly rejected"
    else
        record_test "TS3.3" "Invalid URL rejection" "SKIP" "Unexpected response"
    fi

    echo ""
}

# Main test execution
main() {
    # Verify prerequisites
    echo -e "${YELLOW}Verifying prerequisites...${NC}"

    if ! command -v $KUBECTL_CMD &> /dev/null; then
        echo -e "${RED}Error: $KUBECTL_CMD command not found${NC}"
        exit 1
    fi

    if ! $KUBECTL_CMD get namespace $NAMESPACE &> /dev/null; then
        echo -e "${RED}Error: Namespace $NAMESPACE not found${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Prerequisites verified${NC}"
    echo ""

    # Run requested test suites
    if [ "$TEST_SUITE" == "all" ] || [ "$TEST_SUITE" == "frontend" ]; then
        test_frontend_validation
    fi

    if [ "$TEST_SUITE" == "all" ] || [ "$TEST_SUITE" == "backend" ]; then
        test_backend_binding
    fi

    if [ "$TEST_SUITE" == "all" ] || [ "$TEST_SUITE" == "api" ]; then
        test_data_resolver_api
    fi

    # Display summary
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                     Test Summary                           ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Total Tests:${NC}   $TOTAL_TESTS"
    echo -e "${GREEN}Passed:${NC}        $PASSED_TESTS"
    echo -e "${RED}Failed:${NC}        $FAILED_TESTS"
    echo -e "${YELLOW}Skipped:${NC}       $SKIPPED_TESTS"
    echo ""

    if [ $FAILED_TESTS -eq 0 ]; then
        echo -e "${GREEN}✓ All tests passed or skipped (IPv4-only clusters expected)${NC}"
        exit 0
    else
        echo -e "${RED}✗ Some tests failed${NC}"
        exit 1
    fi
}

# Run main function
main
