# Example CheCluster Custom Resource with explicit image definitions
# Use this with --che-operator-cr-yaml to pre-define all images for mirroring
#
# Usage:
#   ./deploy-che-ipv6.sh --che-operator-cr-yaml examples/custom-checluster-cr.yaml
#
# This CR explicitly defines all container images, which helps with:
# 1. Pre-discovery of images for mirroring (extract with: grep -oE 'image: .+' this-file.yaml)
# 2. Ensuring consistent image versions across all components
# 3. Using mirrored/custom images from internal registries

apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  components:
    # Che Server component
    cheServer:
      debug: false
      logLevel: INFO
      deployment:
        containers:
          - name: che-server
            image: quay.io/eclipse/che-server:next
            imagePullPolicy: Always
            resources:
              limits:
                memory: 1Gi
                cpu: 1000m
              requests:
                memory: 512Mi
                cpu: 100m

    # Dashboard component
    dashboard:
      deployment:
        containers:
          - name: dashboard
            # For IPv6 URL validation testing, use pr-1442
            image: quay.io/eclipse/che-dashboard:pr-1442
            imagePullPolicy: Always
            resources:
              limits:
                memory: 256Mi
              requests:
                memory: 128Mi

    # Plugin Registry component
    pluginRegistry:
      deployment:
        containers:
          - name: plugin-registry
            image: quay.io/eclipse/che-plugin-registry:next
            imagePullPolicy: Always
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi

    # Devfile Registry component
    devfileRegistry:
      deployment:
        containers:
          - name: devfile-registry
            image: quay.io/eclipse/che-devfile-registry:next
            imagePullPolicy: Always
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi

    # DevWorkspace Operator components
    devWorkspace:
      deployment:
        containers:
          # DevWorkspace Controller
          - name: devworkspace-controller
            image: quay.io/devfile/devworkspace-controller:next
            imagePullPolicy: Always
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi

          # DevWorkspace Webhook Server
          - name: devworkspace-webhook-server
            image: quay.io/devfile/devworkspace-controller:next
            imagePullPolicy: Always
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi

    # Image Puller (optional - helps pre-pull common workspace images)
    imagePuller:
      enable: false
      spec:
        images:
          # Universal Developer Image (UDI) - commonly used workspace image
          - name: universal-developer-image
            image: quay.io/devfile/universal-developer-image:ubi9-latest

  # Networking configuration
  networking:
    # For OpenShift, domain is auto-detected from routes
    # tlsSecretName is auto-generated
    auth:
      # OpenShift OAuth integration
      identityProviderURL: ""

  # Container registry configuration (optional)
  containerRegistry:
    # For mirrored images in internal registry
    # hostname: image-registry.openshift-image-registry.svc:5000
    # organization: eclipse-che

  # DevWorkspace configuration
  devEnvironments:
    # Default editor (VS Code)
    defaultEditor: che-incubator/che-code/latest

    # Default workspace images
    defaultComponents:
      - name: universal-developer-image
        container:
          image: quay.io/devfile/universal-developer-image:ubi9-latest
          memoryLimit: 4Gi
          memoryRequest: 2Gi

    # Project clone container
    projectClone:
      image: quay.io/devfile/project-clone:next

    # Storage configuration
    storage:
      pvcStrategy: per-workspace
      # Storage class (auto-detected on OpenShift)
      # pvcStorageClassName: ""

    # Security context
    securityContext:
      fsGroup: 0
      runAsUser: 0

    # Startup timeout (increased for IPv6-only clusters)
    startTimeoutSeconds: 600  # 10 minutes (default: 300)

    # Workspace pod tolerations for scheduling
    tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300

  # Git services configuration
  gitServices:
    # GitHub OAuth (optional)
    github: []
    # GitLab OAuth (optional)
    gitlab: []
    # Bitbucket OAuth (optional)
    bitbucket: []

---
# Additional images that may be pulled during workspace creation
# (not part of CheCluster CR, but useful for mirror discovery)
#
# These images should be added to your mirror-images-to-registry.sh list:
#
# Workspace runtime images:
# - quay.io/devfile/universal-developer-image:ubi9-latest
# - quay.io/devfile/project-clone:next
#
# Plugin images:
# - quay.io/eclipse/che-code:latest (VS Code editor)
# - quay.io/eclipse/che-idea:next (IntelliJ IDEA editor)
# - quay.io/eclipse/che-plugin-sidecar:latest
#
# Gateway/proxy images:
# - quay.io/eclipse/che-gateway:next
# - quay.io/openshift/origin-oauth-proxy:4.9
# - quay.io/openshift/origin-kube-rbac-proxy:4.9
#
# To extract all images from this file:
# grep -oE 'image: [^ ]+' examples/custom-checluster-cr.yaml | awk '{print $2}' | sort -u
