#!/bin/bash
# Mirror Eclipse Che images to local IPv6 cluster registry
#
# This script mirrors all required images for Eclipse Che deployment
# to a local registry that's accessible from an IPv6-only cluster.
#
# Prerequisites:
# - skopeo installed (for image mirroring)
# - oc CLI configured with cluster access
# - Access to local registry
#
# Usage:
#   ./mirror-images-to-registry.sh [options]
#
# Options:
#   --kubeconfig <file>      Path to kubeconfig file (uses proxy-url from kubeconfig)
#   --registry <host:port>   Local registry (default: auto-detect from cluster)
#   --namespace <namespace>  Che namespace (default: eclipse-che)
#   --dashboard-image <image> Dashboard image (default: quay.io/eclipse/che-dashboard:pr-1442)
#   --mode <minimal|full>    Images set to mirror:
#                             - minimal: Che + registries + cert-manager (no DevWorkspace/UDI)
#                             - full:    minimal + DevWorkspace images + UDI (recommended for workspace tests)
#   --quay-creds <user:pass> Optional Quay credentials for private images (used as --src-creds for skopeo)
#   --dry-run               Show what would be mirrored without doing it
#   --help                  Show this help message
#
# Generated by Claude Sonnet 4.5
#
# Generated by GPT-5.2

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
LOCAL_REGISTRY=""
NAMESPACE="eclipse-che"
DASHBOARD_IMAGE="quay.io/eclipse/che-dashboard:pr-1442"
CHE_OPERATOR_IMAGE="quay.io/eclipse/che-operator:next"
MODE="full"
QUAY_CREDS="${QUAY_CREDS:-}"
DRY_RUN=false
KUBECONFIG_FILE=""

# Helpers
extract_proxy_url_from_kubeconfig() {
    # Reads the first "proxy-url:" entry from the kubeconfig (cluster-bot kubeconfigs often include it).
    # Returns empty string if not found.
    local kc="${1:-}"
    if [ -n "${kc}" ] && [ -f "${kc}" ]; then
        grep -m1 'proxy-url:' "${kc}" 2>/dev/null | awk '{print $2}' || true
    else
        grep -m1 'proxy-url:' "${KUBECONFIG:-}" 2>/dev/null | awk '{print $2}' || true
    fi
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig)
            KUBECONFIG_FILE="$2"
            shift 2
            ;;
        --registry)
            LOCAL_REGISTRY="$2"
            shift 2
            ;;
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --dashboard-image)
            DASHBOARD_IMAGE="$2"
            shift 2
            ;;
        --mode)
            MODE="$2"
            shift 2
            ;;
        --quay-creds)
            QUAY_CREDS="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            grep '^#' "$0" | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Validate mode
if [ "${MODE}" != "minimal" ] && [ "${MODE}" != "full" ]; then
    echo -e "${RED}Error: Invalid --mode '${MODE}'. Expected 'minimal' or 'full'.${NC}"
    exit 1
fi

# Set KUBECONFIG if provided
if [ -n "$KUBECONFIG_FILE" ]; then
    if [ ! -f "$KUBECONFIG_FILE" ]; then
        echo -e "${RED}Error: Kubeconfig file not found: $KUBECONFIG_FILE${NC}"
        exit 1
    fi
    export KUBECONFIG="$KUBECONFIG_FILE"
    echo -e "${GREEN}✓ Using kubeconfig: $KUBECONFIG_FILE${NC}"
    echo ""
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Mirror Eclipse Che Images to Local Registry           ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Step 1: Checking prerequisites${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

if ! command -v skopeo &> /dev/null; then
    echo -e "${RED}Error: skopeo not found${NC}"
    echo ""
    echo "Install skopeo:"
    echo "  # macOS"
    echo "  brew install skopeo"
    echo ""
    echo "  # RHEL/Fedora"
    echo "  sudo dnf install skopeo"
    echo ""
    echo "  # Ubuntu/Debian"
    echo "  sudo apt-get install skopeo"
    exit 1
fi
echo -e "${GREEN}✓ skopeo found: $(skopeo --version | head -1)${NC}"

if ! command -v oc &> /dev/null; then
    echo -e "${RED}Error: oc not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ oc CLI found${NC}"

# Auto-detect local registry from cluster (cluster-bot clusters usually have this configured).
if [ -z "$LOCAL_REGISTRY" ]; then
    echo -e "${YELLOW}Auto-detecting local registry from cluster...${NC}"
    LOCAL_REGISTRY=$(oc get imagecontentsourcepolicy -o jsonpath='{.items[0].spec.repositoryDigestMirrors[0].mirrors[0]}' 2>/dev/null | sed 's|/.*||' || echo "")

    if [ -z "$LOCAL_REGISTRY" ]; then
        echo -e "${RED}Error: Could not auto-detect local registry${NC}"
        echo "Please specify with --registry flag"
        exit 1
    fi
    echo -e "${GREEN}✓ Detected registry: ${LOCAL_REGISTRY}${NC}"
fi

# Get registry credentials
echo -e "${YELLOW}Extracting registry credentials...${NC}"
REGISTRY_USER=""
REGISTRY_PASS=""

# Extract destination registry basic auth (if present) from the cluster pull-secret
REGISTRY_AUTH=$(oc get secret pull-secret -n openshift-config -o jsonpath='{.data.\.dockerconfigjson}' 2>/dev/null | base64 -d | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['auths'].get('${LOCAL_REGISTRY}', {}).get('auth', ''))" || echo "")

if [ -z "$REGISTRY_AUTH" ]; then
    echo -e "${YELLOW}⚠ No auth found for ${LOCAL_REGISTRY}, will try without authentication${NC}"
else
    # Decode base64 auth (format: username:password)
    REGISTRY_CREDS=$(echo "$REGISTRY_AUTH" | base64 -d)
    REGISTRY_USER=$(echo "$REGISTRY_CREDS" | cut -d: -f1)
    REGISTRY_PASS=$(echo "$REGISTRY_CREDS" | cut -d: -f2-)
    echo -e "${GREEN}✓ Found credentials for ${LOCAL_REGISTRY} (user: ${REGISTRY_USER})${NC}"
fi

echo ""

# Define images to mirror
echo -e "${YELLOW}Step 2: Defining images to mirror${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# List of images to mirror (bash 3.2 compatible)
IMAGES=()

# Base set (required for Che core + registries)
IMAGES+=(
  "${CHE_OPERATOR_IMAGE}"
  "${DASHBOARD_IMAGE}"
  "quay.io/eclipse/che-server:next"
  "quay.io/che-incubator/configbump:latest"

  # Cert-manager images (used on non-OpenShift / sometimes still referenced)
  "quay.io/jetstack/cert-manager-controller:v1.14.2"
  "quay.io/jetstack/cert-manager-webhook:v1.14.2"
  "quay.io/jetstack/cert-manager-cainjector:v1.14.2"
  "quay.io/jetstack/cert-manager-acmesolver:v1.14.2"

  # Registries (Che components)
  "quay.io/eclipse/che-plugin-registry:next"
  "quay.io/eclipse/che-devfile-registry:next"
)

# Full set adds DevWorkspace + UDI, required for workspace creation tests.
if [ "${MODE}" = "full" ]; then
  IMAGES+=(
    "quay.io/devfile/devworkspace-controller:next"
    "quay.io/devfile/project-clone:next"
    "quay.io/devfile/universal-developer-image:ubi9-latest"
  )
fi

echo "Will mirror ${#IMAGES[@]} images:"
for SOURCE_IMAGE in "${IMAGES[@]}"; do
    echo "  - ${SOURCE_IMAGE}"
done
echo ""

# Mirror images
echo -e "${YELLOW}Step 3: Mirroring images${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

MIRRORED=0
FAILED=0

# Use kubeconfig proxy-url (if present) for tools that do NOT honor kubeconfig proxy-url (e.g. skopeo).
# Important: keep quay.io and RH registries in NO_PROXY so we can pull directly, while pushing to the
# cluster-local registry via the proxy.
PROXY_URL="$(extract_proxy_url_from_kubeconfig "${KUBECONFIG_FILE}")"
SKOPEO_ENV_PREFIX=""
if [ -n "${PROXY_URL}" ]; then
    SKOPEO_ENV_PREFIX="HTTP_PROXY=${PROXY_URL} HTTPS_PROXY=${PROXY_URL} NO_PROXY=localhost,127.0.0.1,quay.io,registry.redhat.io,registry.access.redhat.com"
    echo -e "${YELLOW}Using kubeconfig proxy for skopeo push: ${PROXY_URL}${NC}"
fi

DEST_TLS_VERIFY_FLAG="--dest-tls-verify=false"

for SOURCE_IMAGE in "${IMAGES[@]}"; do

    # Determine destination path
    # Strip registry and just keep the path
    IMAGE_PATH=$(echo "$SOURCE_IMAGE" | sed 's|^[^/]*/||')
    DEST_IMAGE="${LOCAL_REGISTRY}/eclipse-che/${IMAGE_PATH}"

    # Extract image name for display
    IMAGE_NAME=$(echo "$SOURCE_IMAGE" | awk -F'/' '{print $NF}')

    echo -e "${BLUE}Mirroring: ${IMAGE_NAME}${NC}"
    echo "  From: ${SOURCE_IMAGE}"
    echo "  To:   ${DEST_IMAGE}"

    if [ "$DRY_RUN" == "true" ]; then
        echo -e "${YELLOW}  [DRY RUN] Would mirror image${NC}"
        MIRRORED=$((MIRRORED + 1))
        continue
    fi

    # Build skopeo command
    SKOPEO_CMD="skopeo copy --all"

    # Add optional source creds (useful when some quay.io orgs require auth)
    if [ -n "${QUAY_CREDS}" ]; then
        SKOPEO_CMD="${SKOPEO_CMD} --src-creds ${QUAY_CREDS}"
    fi

    # Add destination credentials if available
    if [ -n "${REGISTRY_USER}" ] && [ -n "${REGISTRY_PASS}" ]; then
        SKOPEO_CMD="${SKOPEO_CMD} --dest-creds ${REGISTRY_USER}:${REGISTRY_PASS}"
    fi

    # Add source (always use anonymous for public registries)
    SKOPEO_CMD="${SKOPEO_CMD} ${DEST_TLS_VERIFY_FLAG}"
    SKOPEO_CMD="${SKOPEO_CMD} docker://${SOURCE_IMAGE} docker://${DEST_IMAGE}"

    # Execute mirroring (with retries, useful for transient proxy/network issues like broken pipes)
    MIRROR_OK=false
    for attempt in 1 2 3; do
        if [ -n "${SKOPEO_ENV_PREFIX}" ]; then
            if eval ${SKOPEO_ENV_PREFIX} ${SKOPEO_CMD}; then
                MIRROR_OK=true
                break
            fi
        elif eval ${SKOPEO_CMD}; then
            MIRROR_OK=true
            break
        fi

        if [ "${attempt}" -lt 3 ]; then
            echo -e "${YELLOW}  ⚠ Mirror failed (attempt ${attempt}/3), retrying...${NC}"
            sleep $((attempt * 10))
        fi
    done

    if [ "${MIRROR_OK}" = "true" ]; then
        echo -e "${GREEN}  ✓ Mirrored successfully${NC}"
        MIRRORED=$((MIRRORED + 1))
    else
        echo -e "${RED}  ✗ Failed to mirror${NC}"
        FAILED=$((FAILED + 1))
    fi
    echo ""
done

echo -e "${GREEN}✓ Mirrored ${MIRRORED} images${NC}"
if [ $FAILED -gt 0 ]; then
    echo -e "${RED}✗ Failed to mirror ${FAILED} images${NC}"
fi
echo ""

if [ "$DRY_RUN" == "true" ]; then
    echo -e "${YELLOW}DRY RUN completed. No images were actually mirrored.${NC}"
    exit 0
fi

if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Error: Some images failed to mirror; not applying ImageContentSourcePolicy.${NC}"
    echo -e "${YELLOW}Fix the failures and re-run, or use --dry-run to verify the plan.${NC}"
    exit 1
fi

# Update ImageContentSourcePolicy
echo -e "${YELLOW}Step 4: Creating ImageContentSourcePolicy${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

cat > /tmp/che-image-policy.yaml <<EOF
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: che-images
spec:
  repositoryDigestMirrors:
  # Eclipse Che images
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/eclipse
    source: quay.io/eclipse
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/che-incubator
    source: quay.io/che-incubator

  # Cert-manager images
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/jetstack
    source: quay.io/jetstack
EOF

if [ "${MODE}" = "full" ]; then
cat >> /tmp/che-image-policy.yaml <<EOF

  # DevWorkspace images (required for workspace creation)
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/devfile
    source: quay.io/devfile
EOF
fi

echo "Created ImageContentSourcePolicy:"
cat /tmp/che-image-policy.yaml
echo ""

echo -e "${YELLOW}Applying ImageContentSourcePolicy...${NC}"
oc apply -f /tmp/che-image-policy.yaml

echo -e "${GREEN}✓ ImageContentSourcePolicy applied${NC}"
echo ""

echo -e "${YELLOW}⚠ WARNING: Nodes will reboot to apply new image policy${NC}"
echo -e "${YELLOW}  This may take 10-15 minutes${NC}"
echo ""

# Monitor node reboots
echo -e "${YELLOW}Step 5: Monitoring node updates${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo "Waiting for MachineConfigPool updates..."
echo "You can monitor with: oc get mcp -w"
echo ""

# Display summary
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Image Mirroring Completed Successfully!           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}Summary:${NC}"
echo "  Images mirrored:  ${MIRRORED}"
echo "  Failed:           ${FAILED}"
echo "  Registry:         ${LOCAL_REGISTRY}"
echo "  Policy:           che-images"
echo ""

echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Wait for nodes to apply new image policy (10-15 min)"
echo "     Monitor: oc get mcp -w"
echo ""
echo "  2. Verify nodes are Ready:"
echo "     oc get nodes"
echo ""
echo "  3. Deploy Eclipse Che:"
echo "     ./deploy-che-ipv6-chectl.sh"
echo ""

echo -e "${BLUE}Troubleshooting:${NC}"
echo "  Check mirrored images:"
echo "    oc get imagecontentsourcepolicy che-images"
echo ""
echo "  Verify image policy status:"
echo "    oc get mcp"
echo ""
echo "  Check node status:"
echo "    oc get nodes"
echo ""

echo -e "${GREEN}✓ Image mirroring complete!${NC}"
