#!/bin/bash
# Mirror Eclipse Che images to local IPv6 cluster registry
#
# This script mirrors all required images for Eclipse Che deployment
# to a local registry that's accessible from an IPv6-only cluster.
#
# Prerequisites:
# - skopeo installed (for image mirroring)
# - oc CLI configured with cluster access
# - Access to local registry
#
# Usage:
#   ./mirror-images-to-registry.sh [options]
#
# Options:
#   --kubeconfig <file>      Path to kubeconfig file (uses proxy-url from kubeconfig)
#   --registry <host:port>   Local registry (default: auto-detect from cluster)
#   --namespace <namespace>  Che namespace (default: eclipse-che)
#   --dashboard-image <image> Dashboard image (default: quay.io/eclipse/che-dashboard:pr-1442)
#   --dry-run               Show what would be mirrored without doing it
#   --help                  Show this help message
#
# Generated by Claude Sonnet 4.5

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
LOCAL_REGISTRY=""
NAMESPACE="eclipse-che"
DASHBOARD_IMAGE="quay.io/eclipse/che-dashboard:pr-1442"
CHE_OPERATOR_IMAGE="quay.io/eclipse/che-operator:next"
DRY_RUN=false
KUBECONFIG_FILE=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig)
            KUBECONFIG_FILE="$2"
            shift 2
            ;;
        --registry)
            LOCAL_REGISTRY="$2"
            shift 2
            ;;
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --dashboard-image)
            DASHBOARD_IMAGE="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            grep '^#' "$0" | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Set KUBECONFIG if provided
if [ -n "$KUBECONFIG_FILE" ]; then
    if [ ! -f "$KUBECONFIG_FILE" ]; then
        echo -e "${RED}Error: Kubeconfig file not found: $KUBECONFIG_FILE${NC}"
        exit 1
    fi
    export KUBECONFIG="$KUBECONFIG_FILE"
    echo -e "${GREEN}✓ Using kubeconfig: $KUBECONFIG_FILE${NC}"
    echo ""
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Mirror Eclipse Che Images to Local Registry           ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Step 1: Checking prerequisites${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

if ! command -v skopeo &> /dev/null; then
    echo -e "${RED}Error: skopeo not found${NC}"
    echo ""
    echo "Install skopeo:"
    echo "  # macOS"
    echo "  brew install skopeo"
    echo ""
    echo "  # RHEL/Fedora"
    echo "  sudo dnf install skopeo"
    echo ""
    echo "  # Ubuntu/Debian"
    echo "  sudo apt-get install skopeo"
    exit 1
fi
echo -e "${GREEN}✓ skopeo found: $(skopeo --version | head -1)${NC}"

if ! command -v oc &> /dev/null; then
    echo -e "${RED}Error: oc not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ oc CLI found${NC}"

# Auto-detect local registry from cluster
if [ -z "$LOCAL_REGISTRY" ]; then
    echo -e "${YELLOW}Auto-detecting local registry from cluster...${NC}"
    LOCAL_REGISTRY=$(oc get imagecontentsourcepolicy -o jsonpath='{.items[0].spec.repositoryDigestMirrors[0].mirrors[0]}' 2>/dev/null | sed 's|/.*||' || echo "")

    if [ -z "$LOCAL_REGISTRY" ]; then
        echo -e "${RED}Error: Could not auto-detect local registry${NC}"
        echo "Please specify with --registry flag"
        exit 1
    fi
    echo -e "${GREEN}✓ Detected registry: ${LOCAL_REGISTRY}${NC}"
fi

# Get registry credentials
echo -e "${YELLOW}Extracting registry credentials...${NC}"
REGISTRY_AUTH=$(oc get secret pull-secret -n openshift-config -o jsonpath='{.data.\.dockerconfigjson}' 2>/dev/null | base64 -d | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['auths'].get('${LOCAL_REGISTRY}', {}).get('auth', ''))" || echo "")

if [ -z "$REGISTRY_AUTH" ]; then
    echo -e "${YELLOW}⚠ No auth found for ${LOCAL_REGISTRY}, will try without authentication${NC}"
    REGISTRY_CREDS=""
else
    # Decode base64 auth (format: username:password)
    REGISTRY_CREDS=$(echo "$REGISTRY_AUTH" | base64 -d)
    REGISTRY_USER=$(echo "$REGISTRY_CREDS" | cut -d: -f1)
    REGISTRY_PASS=$(echo "$REGISTRY_CREDS" | cut -d: -f2-)
    echo -e "${GREEN}✓ Found credentials for ${LOCAL_REGISTRY} (user: ${REGISTRY_USER})${NC}"
fi

echo ""

# Define images to mirror
echo -e "${YELLOW}Step 2: Defining images to mirror${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# List of images to mirror (bash 3.2 compatible)
IMAGES=(
    # Eclipse Che images
    "${CHE_OPERATOR_IMAGE}"
    "${DASHBOARD_IMAGE}"
    "quay.io/eclipse/che-server:next"
    "quay.io/eclipse/che--traefik:v2.11.12"
    "quay.io/che-incubator/configbump:latest"

    # Cert-manager images
    "quay.io/jetstack/cert-manager-controller:v1.14.2"
    "quay.io/jetstack/cert-manager-webhook:v1.14.2"
    "quay.io/jetstack/cert-manager-cainjector:v1.14.2"
    "quay.io/jetstack/cert-manager-acmesolver:v1.14.2"

    # DevWorkspace Operator images
    "quay.io/devfile/devworkspace-controller:next"
    "quay.io/devfile/devworkspace-webhook-server:next"
    "quay.io/devfile/project-clone:next"

    # Universal Developer Image (for workspaces)
    "quay.io/devfile/universal-developer-image:ubi9-latest"

    # Plugin registry
    "quay.io/eclipse/che-plugin-registry:next"

    # Devfile registry
    "quay.io/eclipse/che-devfile-registry:next"
)

echo "Will mirror ${#IMAGES[@]} images:"
for SOURCE_IMAGE in "${IMAGES[@]}"; do
    echo "  - ${SOURCE_IMAGE}"
done
echo ""

# Mirror images
echo -e "${YELLOW}Step 3: Mirroring images${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

MIRRORED=0
FAILED=0

for SOURCE_IMAGE in "${IMAGES[@]}"; do

    # Determine destination path
    # Strip registry and just keep the path
    IMAGE_PATH=$(echo "$SOURCE_IMAGE" | sed 's|^[^/]*/||')
    DEST_IMAGE="${LOCAL_REGISTRY}/eclipse-che/${IMAGE_PATH}"

    # Extract image name for display
    IMAGE_NAME=$(echo "$SOURCE_IMAGE" | awk -F'/' '{print $NF}')

    echo -e "${BLUE}Mirroring: ${IMAGE_NAME}${NC}"
    echo "  From: ${SOURCE_IMAGE}"
    echo "  To:   ${DEST_IMAGE}"

    if [ "$DRY_RUN" == "true" ]; then
        echo -e "${YELLOW}  [DRY RUN] Would mirror image${NC}"
        MIRRORED=$((MIRRORED + 1))
        continue
    fi

    # Build skopeo command
    SKOPEO_CMD="skopeo copy --all"

    # Add destination credentials if available
    if [ -n "$REGISTRY_USER" ] && [ -n "$REGISTRY_PASS" ]; then
        SKOPEO_CMD="$SKOPEO_CMD --dest-creds ${REGISTRY_USER}:${REGISTRY_PASS}"
    fi

    # Add source (always use anonymous for public registries)
    SKOPEO_CMD="$SKOPEO_CMD docker://${SOURCE_IMAGE} docker://${DEST_IMAGE}"

    # Execute mirroring
    if eval $SKOPEO_CMD; then
        echo -e "${GREEN}  ✓ Mirrored successfully${NC}"
        MIRRORED=$((MIRRORED + 1))
    else
        echo -e "${RED}  ✗ Failed to mirror${NC}"
        FAILED=$((FAILED + 1))
    fi
    echo ""
done

echo -e "${GREEN}✓ Mirrored ${MIRRORED} images${NC}"
if [ $FAILED -gt 0 ]; then
    echo -e "${RED}✗ Failed to mirror ${FAILED} images${NC}"
fi
echo ""

if [ "$DRY_RUN" == "true" ]; then
    echo -e "${YELLOW}DRY RUN completed. No images were actually mirrored.${NC}"
    exit 0
fi

# Update ImageContentSourcePolicy
echo -e "${YELLOW}Step 4: Creating ImageContentSourcePolicy${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

cat > /tmp/che-image-policy.yaml <<EOF
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: che-images
spec:
  repositoryDigestMirrors:
  # Eclipse Che images
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/eclipse
    source: quay.io/eclipse
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/che-incubator
    source: quay.io/che-incubator

  # Cert-manager images
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/jetstack
    source: quay.io/jetstack

  # DevWorkspace images
  - mirrors:
    - ${LOCAL_REGISTRY}/eclipse-che/devfile
    source: quay.io/devfile
EOF

echo "Created ImageContentSourcePolicy:"
cat /tmp/che-image-policy.yaml
echo ""

echo -e "${YELLOW}Applying ImageContentSourcePolicy...${NC}"
oc apply -f /tmp/che-image-policy.yaml

echo -e "${GREEN}✓ ImageContentSourcePolicy applied${NC}"
echo ""

echo -e "${YELLOW}⚠ WARNING: Nodes will reboot to apply new image policy${NC}"
echo -e "${YELLOW}  This may take 10-15 minutes${NC}"
echo ""

# Monitor node reboots
echo -e "${YELLOW}Step 5: Monitoring node updates${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo "Waiting for MachineConfigPool updates..."
echo "You can monitor with: oc get mcp -w"
echo ""

# Display summary
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Image Mirroring Completed Successfully!           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}Summary:${NC}"
echo "  Images mirrored:  ${MIRRORED}"
echo "  Failed:           ${FAILED}"
echo "  Registry:         ${LOCAL_REGISTRY}"
echo "  Policy:           che-images"
echo ""

echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Wait for nodes to apply new image policy (10-15 min)"
echo "     Monitor: oc get mcp -w"
echo ""
echo "  2. Verify nodes are Ready:"
echo "     oc get nodes"
echo ""
echo "  3. Deploy Eclipse Che:"
echo "     ./deploy-che-ipv6-chectl.sh"
echo ""

echo -e "${BLUE}Troubleshooting:${NC}"
echo "  Check mirrored images:"
echo "    oc get imagecontentsourcepolicy che-images"
echo ""
echo "  Verify image policy status:"
echo "    oc get mcp"
echo ""
echo "  Check node status:"
echo "    oc get nodes"
echo ""

echo -e "${GREEN}✓ Image mirroring complete!${NC}"
