#!/bin/bash
#
# Copyright (c) 2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

# IPv6 Test Infrastructure Deployment for Eclipse Che
#
# This script deploys test infrastructure on IPv6-only OpenShift clusters
# to validate Eclipse Che Dashboard PR-1442 IPv6 URL support.
#
# Infrastructure deployed:
#
# 1. Devfile HTTP Server (Python-based, serves devfiles via IPv6)
#    - Hosts sample devfiles (Node.js, Python) at http://[IPv6]:8080/
#    - Provides index.json with list of available devfiles
#    - Can mirror and serve external devfiles from registry.devfile.io
#    - Purpose: Test Che Dashboard's ability to fetch devfiles from IPv6 URLs
#
# 2. Git HTTP Server (lighttpd-based, serves git repositories via IPv6)
#    - Hosts git repositories at http://[IPv6]:8080/*.git
#    - Supports GitHub-style URLs: http://[IPv6]:8080/user/repo
#    - Includes GitHub API mock endpoints (/api/v3/*)
#    - Purpose: Test Che Dashboard's factory URL parser with IPv6 git URLs
#
# 3. Sample Test Content
#    - Node.js and Python devfiles + git repositories
#    - Optional external repository mirroring
#
# Prerequisites:
# - OpenShift cluster with IPv6 networking
# - oc CLI configured with cluster access
# - Eclipse Che deployed with PR-1442 dashboard
#
# Usage:
#   ./test-ipv6-validation.sh [options]
#
# Options:
#   --kubeconfig <file>   Path to kubeconfig file (uses proxy-url from kubeconfig)
#   --namespace <ns>      Test infrastructure namespace (default: che-test)
#   --che-namespace <ns>  Che namespace (default: eclipse-che)
#   --repo-url <url>      External git repo to mirror and serve over IPv6
#                         Examples:
#                           - git@github.com:che-samples/web-nodejs-sample.git
#                           - https://github.com/che-samples/web-nodejs-sample.git
#   --devfile-url <url>   External devfile URL to mirror and serve over IPv6
#                         Example:
#                           - https://registry.devfile.io/devfiles/nodejs-angular/2.2.1
#   --cleanup            Remove test infrastructure
#   --help               Show this help message
#
# Generated by GPT-5.2

set -euo pipefail

# Get script directory for accessing manifest files
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_DIR="${SCRIPT_DIR}/../manifests"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
NAMESPACE="che-test"
CHE_NAMESPACE="eclipse-che"
CLEANUP=false
KUBECONFIG_FILE=""
REPO_URL=""
DEVFILE_URL=""
EXTERNAL_DEVFILE_URL=""
EXTERNAL_REPO_URL=""
EXTERNAL_REPO_NAME=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --kubeconfig)
            KUBECONFIG_FILE="$2"
            shift 2
            ;;
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --che-namespace)
            CHE_NAMESPACE="$2"
            shift 2
            ;;
        --repo-url)
            REPO_URL="$2"
            shift 2
            ;;
        --devfile-url)
            DEVFILE_URL="$2"
            shift 2
            ;;
        --cleanup)
            CLEANUP=true
            shift
            ;;
        --help)
            grep '^#' "$0" | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Normalize repo URL (convert common SSH GitHub form to https for cloning inside cluster)
REPO_URL_NORM="${REPO_URL}"
REPO_NAME=""
if [ -n "${REPO_URL_NORM}" ]; then
    if echo "${REPO_URL_NORM}" | grep -q '^git@github.com:'; then
        REPO_URL_NORM="$(echo "${REPO_URL_NORM}" | sed 's|^git@github.com:|https://github.com/|')"
    fi
    REPO_NAME="$(basename "${REPO_URL_NORM}")"
    if ! echo "${REPO_NAME}" | grep -q '\.git$'; then
        REPO_NAME="${REPO_NAME}.git"
    fi
fi

# Set KUBECONFIG if provided
if [ -n "$KUBECONFIG_FILE" ]; then
    if [ ! -f "$KUBECONFIG_FILE" ]; then
        echo -e "${RED}Error: Kubeconfig file not found: $KUBECONFIG_FILE${NC}"
        exit 1
    fi
    export KUBECONFIG="$KUBECONFIG_FILE"
    echo -e "${GREEN}✓ Using kubeconfig: $KUBECONFIG_FILE${NC}"
    echo ""
fi

# Cleanup mode
if [ "$CLEANUP" == "true" ]; then
    echo -e "${YELLOW}Cleaning up test infrastructure...${NC}"
    oc delete namespace ${NAMESPACE} --ignore-not-found=true
    echo -e "${GREEN}✓ Test infrastructure removed${NC}"
    exit 0
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║    Deploying IPv6 Test Infrastructure for Che Dashboard   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Step 1: Checking prerequisites${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

if ! command -v oc &> /dev/null; then
    echo -e "${RED}Error: oc command not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ oc CLI found${NC}"

if ! oc whoami &> /dev/null; then
    echo -e "${RED}Error: Not logged into OpenShift cluster${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Logged into cluster as $(oc whoami)${NC}"

# Check if cluster has IPv6
SERVICE_NETS_RAW="$(oc get network.config.openshift.io cluster -o jsonpath='{.status.serviceNetwork[*]}' 2>/dev/null || echo "")"
IPV6_SERVICE="$(echo "${SERVICE_NETS_RAW}" | tr ' ' '\n' | grep ':' | head -1 || true)"
if [ -z "$IPV6_SERVICE" ]; then
    echo -e "${YELLOW}⚠ Warning: Cluster may not have IPv6 networking${NC}"
else
    echo -e "${GREEN}✓ Cluster has IPv6 service network: ${IPV6_SERVICE}${NC}"
fi

echo ""

# Create namespace
echo -e "${YELLOW}Step 2: Creating test namespace${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

oc create namespace ${NAMESPACE} --dry-run=client -o yaml | oc apply -f -
echo -e "${GREEN}✓ Namespace ${NAMESPACE} ready${NC}"
echo ""

# Create sample devfiles
echo -e "${YELLOW}Step 3: Creating sample devfiles${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

export NAMESPACE
envsubst < "${MANIFEST_DIR}/test-infrastructure/devfile-configmaps.yaml" | oc apply -f -

echo -e "${GREEN}✓ Sample devfiles created${NC}"
echo ""

# Create sample repositories
echo -e "${YELLOW}Step 4: Creating sample git repositories${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

envsubst < "${MANIFEST_DIR}/test-infrastructure/repository-configmaps.yaml" | oc apply -f -

echo -e "${GREEN}✓ Sample repositories created${NC}"
echo ""

# Deploy devfile HTTP server
echo -e "${YELLOW}Step 5: Deploying devfile HTTP server${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

export DEVFILE_URL
envsubst < "${MANIFEST_DIR}/test-infrastructure/devfile-server.yaml" | oc apply -f -

echo -e "${GREEN}✓ Devfile server deployed${NC}"
echo ""

# Deploy git HTTP server
echo -e "${YELLOW}Step 6: Deploying git HTTP server${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

export REPO_URL_NORM
export REPO_NAME
envsubst < "${MANIFEST_DIR}/test-infrastructure/git-server.yaml" | oc apply -f -

echo -e "${GREEN}✓ Git server deployed${NC}"
echo ""

# Wait for deployments
echo -e "${YELLOW}Step 7: Waiting for services to be ready${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

echo "Waiting for devfile-server..."
oc rollout status deployment/devfile-server -n ${NAMESPACE} --timeout=120s
echo -e "${GREEN}✓ Devfile server ready${NC}"

echo "Waiting for git-server..."
oc rollout status deployment/git-server -n ${NAMESPACE} --timeout=120s
echo -e "${GREEN}✓ Git server ready${NC}"

echo ""

# Get service IPs
echo -e "${YELLOW}Step 8: Retrieving service information${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

DEVFILE_IPV6=$(oc get service devfile-server -n ${NAMESPACE} -o jsonpath='{.spec.clusterIPs[0]}')
DEVFILE_IPV4=$(oc get service devfile-server -n ${NAMESPACE} -o jsonpath='{.spec.clusterIPs[1]}' 2>/dev/null || echo "N/A")
GIT_IPV6=$(oc get service git-server -n ${NAMESPACE} -o jsonpath='{.spec.clusterIPs[0]}')
GIT_IPV4=$(oc get service git-server -n ${NAMESPACE} -o jsonpath='{.spec.clusterIPs[1]}' 2>/dev/null || echo "N/A")

echo -e "${BLUE}Service Information:${NC}"
echo ""
echo "Devfile Server:"
echo "  IPv6 Address: ${DEVFILE_IPV6}"
echo "  IPv4 Address: ${DEVFILE_IPV4}"
echo "  Service Name: devfile-server.${NAMESPACE}.svc.cluster.local"
echo ""
echo "Git Server:"
echo "  IPv6 Address: ${GIT_IPV6}"
echo "  IPv4 Address: ${GIT_IPV4}"
echo "  Service Name: git-server.${NAMESPACE}.svc.cluster.local"
echo ""

# Test URLs
echo -e "${YELLOW}Step 9: Testing service accessibility${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════${NC}"

# Test devfile server
echo "Testing devfile server..."
TEST_POD=$(oc run test-curl --image=curlimages/curl:latest --rm -i --restart=Never -n ${NAMESPACE} -- curl -s "http://[${DEVFILE_IPV6}]:8080/index.json" 2>&1 || echo "")
if echo "$TEST_POD" | grep -q "nodejs-hello-world"; then
    echo -e "${GREEN}✓ Devfile server responding on IPv6${NC}"
else
    echo -e "${YELLOW}⚠ Could not verify devfile server on IPv6${NC}"
fi

# Test git server
echo "Testing git server..."
TEST_POD=$(oc run test-curl --image=curlimages/curl:latest --rm -i --restart=Never -n ${NAMESPACE} -- curl -s "http://[${GIT_IPV6}]:8080/nodejs-hello-world.git/info/refs?service=git-upload-pack" 2>&1 || echo "")
if echo "$TEST_POD" | grep -q "git-upload-pack"; then
    echo -e "${GREEN}✓ Git server responding on IPv6${NC}"
else
    echo -e "${YELLOW}⚠ Could not verify git server on IPv6${NC}"
fi

echo ""

# Display test URLs
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Test Infrastructure Deployed Successfully!             ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}IPv6 Test URLs for Eclipse Che:${NC}"
echo ""
echo "Devfile Server (IPv6):"
echo "  Index:         http://[${DEVFILE_IPV6}]:8080/index.json"
echo "  Node.js:       http://[${DEVFILE_IPV6}]:8080/nodejs/devfile.yaml"
echo "  Python:        http://[${DEVFILE_IPV6}]:8080/python/devfile.yaml"
echo ""
echo "Git Server (IPv6):"
echo "  Node.js repo:  http://[${GIT_IPV6}]:8080/nodejs-hello-world.git"
echo "  Python repo:   http://[${GIT_IPV6}]:8080/python-hello-world.git"
echo ""
echo "GitHub-style URLs (IPv6) - for testing GitHub URL parser:"
echo "  Node.js repo:  http://[${GIT_IPV6}]:8080/testuser/nodejs-hello-world"
echo "  Python repo:   http://[${GIT_IPV6}]:8080/testuser/python-hello-world"
echo "  GitHub API:    http://[${GIT_IPV6}]:8080/api/v3/user"
echo ""

if [ -n "${REPO_NAME}" ]; then
    echo "External inputs:"
    echo "  repo-url:     ${REPO_URL}"
    echo "  repo-url (normalized for cloning): ${REPO_URL_NORM}"
    if [ -n "${DEVFILE_URL}" ]; then
        echo "  devfile-url:  ${DEVFILE_URL}"
    else
        echo "  devfile-url:  (not provided)"
    fi
    echo ""
    echo "External repo (mirrored, via IPv6):"
    echo "  http://[${GIT_IPV6}]:8080/${REPO_NAME}"
    if [ -n "${DEVFILE_URL}" ]; then
        echo "  with devfile (mirrored): http://[${GIT_IPV6}]:8080/${REPO_NAME}?df=http://[${DEVFILE_IPV6}]:8080/external/devfile.yaml"
    fi
    echo ""
fi

echo -e "${BLUE}Testing IPv6 URL Support in Che Dashboard:${NC}"
echo ""
echo "IMPORTANT: The cluster proxy does NOT support IPv6 URLs directly in browser."
echo "Use the Che Dashboard API instead:"
echo ""
echo "1. Get Che URL:"
echo "   CHE_URL=\$(oc get checluster eclipse-che -n ${CHE_NAMESPACE} -o jsonpath='{.status.cheURL}')"
echo "   echo \$CHE_URL"
echo ""
echo "2. Launch Chrome with proxy:"
echo "   # macOS"
echo "   killall \"Google Chrome\" 2>/dev/null"
echo "   /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \\"
echo "     --proxy-server=\"\$(grep proxy-url \$KUBECONFIG | awk '{print \$2}')\" \\"
echo "     --user-data-dir=\"/tmp/chrome-che-proxy-\$(date +%s)\" \\"
echo "     --no-first-run \\"
echo "     \"\${CHE_URL}/dashboard/api/swagger/static/index.html\""
echo ""
echo "3. Test IPv6 URLs via Swagger API (POST /dashboard/api/data/resolver):"
echo ""
echo "   Test devfile index:"
echo "   {\"url\": \"http://[${DEVFILE_IPV6}]:8080/index.json\"}"
echo ""
echo "   Test Node.js devfile:"
echo "   {\"url\": \"http://[${DEVFILE_IPV6}]:8080/nodejs/devfile.yaml\"}"
echo ""
echo "   Test Python devfile:"
echo "   {\"url\": \"http://[${DEVFILE_IPV6}]:8080/python/devfile.yaml\"}"
echo ""
echo "   Test GitHub-style URL (tests GitHub URL parser with IPv6):"
echo "   {\"url\": \"http://[${GIT_IPV6}]:8080/testuser/nodejs-hello-world\"}"
echo ""
echo "4. Expected result: HTTP 200 with devfile content (confirms IPv6 URL support works)"
echo ""

echo -e "${BLUE}Cleanup:${NC}"
echo "  ./test-ipv6-validation.sh --cleanup"
echo ""

echo -e "${GREEN}✓ Ready for IPv6 testing!${NC}"
